server:
  port: 8081

spring:
  docker:
    compose:
      file: "classpath:docker/compose.yaml"

cgdpd:
  http:
    server:
      authorized-clients:
        - username: FrontendApi
          password: FrontendApiSecret
          role: NORMAL

logging:
  level:
    root: INFO
    com.cgdpd.library: DEBUG
    org:
      hibernate:
        SQL: INFO
        type: INFO
    net.ttddyy.dsproxy.listener: DEBUG
