spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    clean-disabled: false

logging:
  level:
    root: INFO
    com.cgdpd.library: DEBUG
    org:
      hibernate:
        SQL: INFO
        type: INFO
    net.ttddyy.dsproxy.listener: DEBUG
