spring:
  ## Configs to generate sql schema based on entities
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: create.sql
              drop-target: drop.sql
              action: create-drop
            create-source: metadata
            drop-source: metadata
    hibernate:
      ddl-auto: create-drop
