logging:
  level:
    root: INFO
    com.cgdpd.library: DEBUG


## Configs to generate sql schema based on entities
spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-target: create.sql
              drop-target: drop.sql
              action: create-drop
            create-source: metadata
            drop-source: metadata
    hibernate:
      ddl-auto: create-drop
