services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=catalog'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=catalog'
    ports:
      - '5432:5432'
